//! Keeps `scripts/doc-screenshots.sh` and the pictures the docs show in step.
//!
//! Every GUI screenshot in `README.md` and `docs/` is regenerated by a scene in
//! that script. A picture added to a doc without a scene is one nobody can
//! refresh; a scene whose picture no doc shows is one nobody looks at. Both
//! drift silently, so this test compares the two lists.
//!
//! It lives in `dmm-gui` because the scenes drive that binary. It reads the
//! script as text rather than running it: the scenes need an X display, and
//! this check has to run in CI.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

const SCRIPT: &str = "scripts/doc-screenshots.sh";

/// `assets/` files that are not screenshots: the app icon ships with the
/// desktop entry.
const NOT_A_SCREENSHOT: &[&str] = &["icon-256.png"];

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repo root")
}

fn script_text() -> String {
    std::fs::read_to_string(repo_root().join(SCRIPT)).expect("read the screenshot script")
}

/// The `(picture, scene function)` pairs in the script's `SCENES` table.
///
/// A scene may write more than one picture, so the same function can appear
/// twice.
fn scenes(script: &str) -> Vec<(String, String)> {
    let table = script
        .split_once("\nSCENES=(\n")
        .expect("a SCENES table in the screenshot script")
        .1;
    let table = table
        .split_once("\n)")
        .expect("the end of the SCENES table")
        .0;
    table
        .lines()
        .filter_map(|line| {
            let entry = line.trim().strip_prefix('"')?.strip_suffix('"')?;
            let (asset, function) = entry.split_once(' ')?;
            Some((asset.to_string(), function.trim().to_string()))
        })
        .collect()
}

/// Every `assets/*.png` the README and the docs show, by file name.
fn pictures_in_the_docs() -> BTreeSet<String> {
    let root = repo_root();
    let mut docs = vec![root.join("README.md")];
    let mut markdown: Vec<PathBuf> = std::fs::read_dir(root.join("docs"))
        .expect("read docs/")
        .filter_map(|entry| {
            let path = entry.expect("docs/ entry").path();
            (path.extension()? == "md").then_some(path)
        })
        .collect();
    markdown.sort();
    docs.append(&mut markdown);

    let mut found = BTreeSet::new();
    for path in docs {
        let text = std::fs::read_to_string(&path).expect("read a doc");
        for (index, _) in text.match_indices("assets/") {
            let name: String = text[index + "assets/".len()..]
                .chars()
                .take_while(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-'))
                .collect();
            if name.ends_with(".png") && !NOT_A_SCREENSHOT.contains(&name.as_str()) {
                found.insert(name);
            }
        }
    }
    found
}

#[test]
fn every_picture_in_the_docs_has_a_scene() {
    let script = script_text();
    let staged: BTreeSet<String> = scenes(&script)
        .into_iter()
        .map(|(asset, _)| asset)
        .collect();
    let shown = pictures_in_the_docs();

    let unshown: Vec<&String> = staged.difference(&shown).collect();
    assert!(
        unshown.is_empty(),
        "{SCRIPT} has a scene for {unshown:?}, which no doc shows — reference the picture or drop its scene"
    );
    let unstaged: Vec<&String> = shown.difference(&staged).collect();
    assert!(
        unstaged.is_empty(),
        "the docs show {unstaged:?}, which no scene in {SCRIPT} regenerates — add a scene or drop the picture"
    );
}

#[test]
fn every_scene_names_a_function_the_script_defines() {
    let script = script_text();
    for (asset, function) in scenes(&script) {
        assert!(
            script.contains(&format!("\n{function}() {{")),
            "the scene for {asset} names {function}(), which {SCRIPT} does not define"
        );
    }
}
