[package]
name = "dmm-gui"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
description = "GUI application for UNI-T and Voltcraft digital multimeters"

[dependencies]
dmm-lib = { path = "../dmm-lib" }
dmm-shared = { path = "../dmm-shared" }
eframe = { version = "0.36", features = ["glow", "wgpu"] }
egui_commonmark = "0.25"
egui_plot = "0.37"
raw-window-handle = "0.6"
chrono.workspace = true
csv.workspace = true
rfd = "0.17"
clap.workspace = true
env_logger.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
directories.workspace = true

[dev-dependencies]
dmm-lib = { path = "../dmm-lib", features = ["test-support"] }
