[package]
name = "dmm-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "GUI application for UNI-T and Voltcraft digital multimeters"

[dependencies]
dmm-lib = { path = "../dmm-lib" }
dmm-settings = { path = "../dmm-settings" }
eframe = { version = "0.34", features = ["glow", "wgpu"] }
egui_commonmark = "0.23"
egui_plot = "0.35"
chrono.workspace = true
csv.workspace = true
rfd = "0.17"
clap.workspace = true
env_logger.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
directories.workspace = true

[dev-dependencies]
dmm-lib = { path = "../dmm-lib", features = ["test-support"] }
